AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 30