REQUIRED_ENV = %w(
  SECRET_KEY_BASE
  AWS_BUCKET
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  IPAYOUT_API_ENDPOINT
  IPAYOUT_AUTO_LOGIN_ENDPOINT
  IPAYOUT_MERCHANT_GUID
  IPAYOUT_MERCHANT_PASSWORD
  SOLAR_CITY_LEAD_URL)
Figaro.require_keys(*REQUIRED_ENV)
