development:
  access_key_id: AKIAIP4IQ77YPIRW5EWA
  secret_access_key: '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'
  bucket: 'sunstand-dev'

test:
  access_key_id: AKIAIP4IQ77YPIRW5EWA
  secret_access_key: '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'
  bucket: 'sunstand-dev'

production:
  access_key_id: AKIAIP4IQ77YPIRW5EWA
  secret_access_key: '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'
  bucket: 'sunstand-dev'
