---
development:
  aws_access_key_id: AKIAIP4IQ77YPIRW5EWA
  aws_secret_access_key: '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'
  aws_bucket: 'sunstand-dev'

test:
  secret_key_base: c067388df669c07808e590a8600622d4d09832398fb48b87a617db1c30f27a54fbd045779921dcb13ad20a593eb0bd6b861eca948ba76d1bddce0773de7f382d
  ipayout_api_endpoint: 'https://testewallet.com/eWalletWS/ws_JsonAdapter.aspx'
  ipayout_auto_login_endpoint: 'https://sunstand.testewallet.com/MemberLogin.aspx?secKey='
  ipayout_merchant_guid: 'a4739056-7db6-40f3-9618-f2bcccbf70cc'
  ipayout_merchant_password: 9xXLvA66hi
  # AMAZON S3
  aws_access_key_id: AKIAIP4IQ77YPIRW5EWA
  aws_secret_access_key: '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'
  aws_bucket: 'sunstand-dev'

staging:
  ipayout_api_endpoint: 'https://testewallet.com/eWalletWS/ws_JsonAdapter.aspx'
  ipayout_auto_login_endpoint: 'https://sunstand.globalewallet.com/MemberLogin.aspx?secKey='
  ipayout_merchant_guid: <%= ENV['IPAYOUT_MERCHANT_GUID'] %>
  ipayout_merchant_password: <%= ENV['IPAYOUT_MERCHANT_PASSWORD'] %>
  # AMAZON S3
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  ipayout_api_endpoint: 'https://testewallet.com/eWalletWS/ws_JsonAdapter.aspx'
  ipayout_auto_login_endpoint: 'https://sunstand.globalewallet.com/MemberLogin.aspx?secKey='
  ipayout_merchant_guid: <%= ENV['IPAYOUT_MERCHANT_GUID'] %>
  ipayout_merchant_password: <%= ENV['IPAYOUT_MERCHANT_PASSWORD'] %>
  # AMAZON S3
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
