# we use https://github.com/laserlemon/figaro for env variable management
# download application.yml from drive at /Development/Powur/03 Documents/application.yml
# application.yml is ignored in git per 12 factor app methodology