
development:
  secret_key_base: 187aca0962adf1334246bf8444b853dca825058ec576685536e6389cff4b1cccc30e18f812f2f77e844f218eb3987781276066c357f6b602f65841261e20f055
  aws_access_key_id: AKIAIP4IQ77YPIRW5EWA
  aws_bucket: sunstand-dev
  aws_secret_access_key: 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
  ipayout_api_endpoint: "https://testewallet.com/eWalletWS/ws_JsonAdapter.aspx"
  ipayout_auto_login_endpoint: "https://sunstand.testewallet.com/MemberLogin.aspx?secKey="
  ipayout_merchant_guid: a4739056-7db6-40f3-9618-f2bcccbf70cc
  ipayout_merchant_password: 9xXLvA66hi
  nmi_api_key: 5034198
  nmi_debug: true
  nmi_merchant_id: sunstand
  nmi_mode: sandbox
  nmi_password: password
  nmi_username: demo
  secret_key_base: 187aca0962adf1334246bf8444b853dca825058ec576685536e6389cff4b1cccc30e18f812f2f77e844f218eb3987781276066c357f6b602f65841261e20f055
production:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  ipayout_api_endpoint: "https://testewallet.com/eWalletWS/ws_JsonAdapter.aspx"
  ipayout_auto_login_endpoint: "https://sunstand.globalewallet.com/MemberLogin.aspx?secKey="
  ipayout_merchant_guid: <%= ENV['IPAYOUT_MERCHANT_GUID'] %>
  ipayout_merchant_password: <%= ENV['IPAYOUT_MERCHANT_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  nmi_api_key: <%= ENV['NMI_API_KEY'] %>
  nmi_debug: false
  nmi_merchant_id: <%= ENV['NMI_MERCHANT_ID'] %>
  nmi_mode: <%= ENV['NMI_MODE'] %>
  nmi_password: <%= ENV['NMI_USERNAME'] %>
  nmi_username: <%= ENV['NMI_PASSWORD'] %>
test:
  secret_key_base: c067388df669c07808e590a8600622d4d09832398fb48b87a617db1c30f27a54fbd045779921dcb13ad20a593eb0bd6b861eca948ba76d1bddce0773de7f382d
  aws_access_key_id: AKIAIP4IQ77YPIRW5EWA
  aws_bucket: sunstand-dev
  aws_secret_access_key: 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
  ipayout_api_endpoint: "https://testewallet.com/eWalletWS/ws_JsonAdapter.aspx"
  ipayout_auto_login_endpoint: "https://sunstand.testewallet.com/MemberLogin.aspx?secKey="
  ipayout_merchant_guid: a4739056-7db6-40f3-9618-f2bcccbf70cc
  ipayout_merchant_password: 9xXLvA66hi
  nmi_api_key: 5034198
  nmi_debug: true
  nmi_merchant_id: sunstand
  nmi_mode: sandbox
  nmi_password: password
  nmi_username: demo
  secret_key_base: c067388df669c07808e590a8600622d4d09832398fb48b87a617db1c30f27a54fbd045779921dcb13ad20a593eb0bd6b861eca948ba76d1bddce0773de7f382d
staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  ipayout_api_endpoint: 'https://testewallet.com/eWalletWS/ws_JsonAdapter.aspx'
  ipayout_auto_login_endpoint: 'https://sunstand.globalewallet.com/MemberLogin.aspx?secKey='
  ipayout_merchant_guid: <%= ENV['IPAYOUT_MERCHANT_GUID'] %>
  ipayout_merchant_password: <%= ENV['IPAYOUT_MERCHANT_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  nmi_api_key: <%= ENV['NMI_API_KEY'] %>
  nmi_debug: false
  nmi_merchant_id: <%= ENV['NMI_MERCHANT_ID'] %>
  nmi_mode: <%= ENV['NMI_MODE'] %>
  nmi_password: <%= ENV['NMI_USERNAME'] %>
  nmi_username: <%= ENV['NMI_PASSWORD'] %>