products:
  - id: 1
    name: Solar Item
    bonus_volume: 1000
    commission_percentage: 80
  - id: 2
    name: "Fast Impact Training (FIT)"
    description: "The “Fast Impact Training” (FIT) is a quick introduction to succeeding as a Powur advocate.  Learn the basics of Solar, and what rules you need to follow to prosper with Powur. This training is required before you can begin enrolling customers or new team mates in Powur."
    bonus_volume: 9900
    distributor_only: 1
    is_university_class: 1
    image_original_path: "https://s3.amazonaws.com/sunstand-dev/seed_data/products/fit.jpg"
    smarteru_module_id: 8319
    is_required_class: 1
    position: 1
  - id: 3
    name: "Powur Energy-Consultant Certification"
    description: "The powur energy-consultant certification makes you an unparalleled leader in the direct selling energy space.  This proprietary certification gives you advanced insights into solar, the energy markets at large, how to sell,  how to build an effective sales organization, and the fastest way to reach your goals. Certification is required to earn commissions from the grid you build."
    long_description: "The Powur Energy-Consultant Certification gives you the knowledge, skills, and tools you need to succeed wildly in the solar revolution. As a certified Powur Consultant you'll have...<br /><ul><li>Access to insider solar industry training to boost the number of homeowners you refer.</li><li>State-of-the-art techniques to grow a team that gives you leveraged, 'royalty' like income.</li><li>Detailed training to help you maximize the Powur compensation plan, making sure you get the most out of your referrals.</li><li>Plus crucial success tips you must know to capitalize on the enormous trends of solar energy, and turn your Powur business into an asset that pays income for decades as we shift from dirty to clean energy.</li></ul>Complete your Powur Energy-Consultant registration below to get certified."
    bonus_volume: 14900
    distributor_only: 1
    is_university_class: 1
    image_original_path: "https://s3.amazonaws.com/sunstand-dev/seed_data/products/certification.jpg"
    smarteru_module_id: 8342
    is_required_class: 0
    position: 1
